
import { Footer } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import { StateProvider } from '@/utils/context'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})
 
 const poppins=Poppins({
  variable: '--font-poppins',
  weight:'700',
  subsets: ['latin'],
  display: 'swap',
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable}`}>
        <div className="container">
          <StateProvider>
            {children}
            <Footer />
          </StateProvider>
        </div>
      </body>
    </html>
  )
}
