export { default as Navbar } from './navbar/NavBar';
export { default as Footer } from './footer/Footer';
export { default as Hire } from './hireMe/HireMe';
export { default as Media } from './media/media';
export { default as Card } from './card/Card';
export { default as Soft } from './softSkill/SoftSkills';
export { default as Tech } from './techSkill/TechSkills';
export { default as Header } from './header/Header';
export { default as VideoPlayer } from './vid/Video';